blog/urls.py
"""Define URL patterns for blog page."""
from django.urls import path
from django.conf.urls import url
from .views import ModuleDetailView, ModuleListView,  InstructorListView, InstructorDetailView, new_module

from . import views
from .models import *
app_name = 'blog'

urlpatterns = [
    # Home page
    path ('', views.index, name ='index'),
    path ('modules/', views.ModuleListView.as_view(), name = 'modules'),# module display url link
    path ('module/<int:pk>', views.ModuleDetailView.as_view(), name= 'module-detail'), # detail information of the list module
    path ('instructors/', views.InstructorListView.as_view(), name='instructors'),
    path ('instructor/<int:pk>', views.InstructorDetailView.as_view(), name= 'instructor-detail'),
    path ('new_module/', views.new_module, name='new_module'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
#from register import views


app_name = 'blog'  # here for namespacing of urls.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls", namespace= "blog")),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique module instances

class Content_Type(models.Model):
    """Model representing a module type."""
    name = models.CharField(max_length=200, help_text='Enter a module type (e.g. Saftey or Benefit)')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Module(models.Model):
    """Model representing a training module."""
    title = models.CharField(max_length=200)

    # Foreign Key used because the training module can only have one instructor, but instructor can have multiple training module
    instructor = models.ForeignKey('Instructor', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the training module')
    code = models.CharField('CODE', max_length=10, unique=True, 
                            help_text='')
    # ManyToManyField used because type can contain many module. Module can cover many types.
    content_type = models.ManyToManyField(Content_Type, help_text='Select a type for this module')
    
    class Meta:
        ordering = ['title']

    def display_content_type(self):
        """Create a string for the content_type. This is required to display type in Admin."""
        return ', '.join(content_type.name for content_type in self.content_type.all()[:3])
    
    display_content_type.short_description = 'Type'
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this module."""
        return reverse('module-detail', kwargs={'pk': self.pk })

    def __str__(self):
        """String for representing the Model object."""
        return self.title

class ModuleInstance(models.Model):
    """Model representing a specific module status."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular module in the training')
    module = models.ForeignKey('Module', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    start_date = models.DateField(null=True, blank=True)

    MODULE_STATUS = (
        ('N', 'Not started'),
        ('P', 'On progress'),
        ('D', 'Done'),
        
    )

    status = models.CharField(
        max_length=1,
        choices=MODULE_STATUS,
        blank=True,
        default='N',
        help_text='Not Started',
    )

    class Meta:
        ordering = ['start_date']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.module.title})'

class Instructor(models.Model):
    """Model representing an instructor."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

    class Meta:
        ordering = ['last_name']
    

    def get_absolute_url(self):
        """Returns the url to access a particular instructor instance."""
        return reverse('instructor-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    

blog/forms.py
from django import forms
from .models import*

class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = ['title','instructor','summary', 'code', 'content_type']

    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView
from blog.models import Module, Instructor, Content_Type, ModuleInstance 
from .forms import ModuleForm
# Create your views here.


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_modules = Module.objects.all().count()   
    num_instructors = Instructor.objects.count()
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_modules': num_modules,
        'num_instructors': num_instructors,
        'num_visits': num_visits,
    }


# Render the HTML template index.html
    return render(request, 'blog/index.html', context=context)

class ModuleListView(ListView):
    """Generic class-based list view for module"""
    #model= Module
    queryset = Module.objects.all()
    paginate_by = 4


class ModuleDetailView(DetailView):
    model = Module
    template_name = 'blog/module_detail.html'
    def get(self, request, *args, **kwargs):
        module = get_object_or_404(Module, pk=kwargs['pk'])
        context = {'module': module}
        return render(request, 'blog/module_detail.html', context)
    
    

class InstructorListView(ListView):
    """Generic class-based list view for a list of instructors."""
    model = Instructor
    paginate_by = 10


class InstructorDetailView(DetailView):
    """Generic class-based detail view for an instructor."""
    model = Instructor
    template_name = 'blog/instructor_detail.html'

def new_module(request):
    """ Add a new module """
    if request.method != 'POST':
        #No data submitted; creat a blank form.
        form = ModuleForm()
    else:
        # POST data submitted; process data
        form = ModuleForm(data= request.POST)
        if form.is_valid():
            form.save()
            return redirect ('blog:modules')

    # Display a blank or invalid form.
    context = {'form': form}
    return render (request, 'blog/new_module.html', context)

blog/templates/blog/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    <title>eTraining</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class='navbar-brand' href="">eTraining</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-lable="toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{% url 'blog:index' %}">Home</a>
                    <a href= "{% url 'blog:new_module' %}"> Add Module</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main id= "wrap" class="container">

        <div id="main" class = "pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                    <ul class="sidebar-nav">
                        
                        <li><a href="{% url 'blog:modules' %}">All Modules</a></li>

                        <li><a href="{% url 'blog:instructors' %}">All Instructors</a></li>
                    </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
                
            </div>
        </div>
        {% block pagination %}
    {% if is_paginated %}
        <div class="pagination justify-content-center">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
    </main>
<!-- Footer -->
<footer class="footer-area footer--light">

   
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href=""> Filmon</a>
    </div>
    
  
  </footer>
 

   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block page_header %}
<div class ="jumbotron">
  <h3 class = "display-3">Attend your Training.</h3>
  <p class ="lead"> By login your creditial start your training of our company. The training focus on the Modules learning such Saftey, Laws and Rules of our company.</p>
</div>
{% endblock page_header %}
{% block content %}
<h1>eTraining Home</h1>

<p>Welcome to <em>eTraining</em>, </p>
<p>eTraining is a great idea in solving the eTraining problem.</p>
<p>eTraining creates a chance for the learning modules and materials on the eTraining web application.</p>

<h2>Content</h2>
<p>Currently, eTraining has the following contents. </p>

<ul>
  <li><strong>Modules:</strong> {{ num_modules }}</li>
  <li><strong>Instructors:</strong> {{ num_instructors }}</li>
</ul>
<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock content %}

blog/templates/blog/instructor_detail.html
{% extends "blog/base.html" %}
{% block page_header %}
<div class ="jumbotron">
    <h3 class = "display-3">Attend your Training.</h3>
    <p class ="lead"> By login your creditial start your training of our company. The training focus on the Modules learning such Saftey, Laws and Rules of our company.</p>
</div>
{% endblock page_header %}
{% block content %}
<h1>Instructors detail</h1>
<div class=" card mb-3">
    <div class="card-header">
        {{ instructor.first_name }} {{instructor.last_name}}</a>
    </div>
    <div class="card-body">
        <p>Contact Email: {{instructor.email}} </p>
        
    </div>
</div>


{% endblock content %}

blog/templates/blog/instructor_list.html
{% extends "blog/base.html" %}
{% block page_header %}
<div class="jumbotron">
    <h3 class="display-3">Attend your Training.</h3>
    <p class="lead"> By login your creditial start your training of our company. The training focus on the Modules
        learning such Saftey, Laws and Rules of our company.</p>
</div>
{% endblock page_header %}
{% block content %}
<h2>Instructors</h2>
{% for instructor in object_list %}
<div class=" card mb-3">
    <div class="card-header"> 
        
        <a href="{% url 'blog:instructor-detail' instructor.pk %}">
            {{ instructor }}
        </a>
        
    </div>
    
    <div class="card-body">
        
            <p>Email: {{ instructor.email }}</p>
        
    </div>
    
</div>



{% if object_list %}

{% else %}
<p>There are no instructor available.</p>
{% endif %}
{% endfor %}
{% endblock %}

blog/templates/blog/module_detail.html
{% extends "blog/base.html" %}
{% block page_header %}
<div class ="jumbotron">
    <h3 class = "display-3">Attend your Training.</h3>
    <p class ="lead"> By login your creditial start your training of our company. The training focus on the Modules learning such Saftey, Laws and Rules of our company.</p>
</div>
{% endblock page_header %}
{% block content %}
<h1>Modules detail</h1>
<div class=" card mb-3">
    <div class="card-header">
        <a href="">{{ module.title }}</a>
    </div>
    <div class="card-body">
        <p>Instructor: <a href="{% url 'blog:instructor-detail' module.instructor.pk %}">{{module.instructor}}</a> </p>
        <p>Summary: {{module.summary}}</p>
        <p><strong>CODE:</strong> {{ module.code }}</p>
    </div>
</div>


{% endblock content %}

blog/templates/blog/module_list.html
{% extends "blog/base.html" %}
{% block page_header %}
<div class="jumbotron">
    <h3 class="display-3">Attend your Training.</h3>
    <p class="lead"> By login your creditial start your training of our company. The training focus on the Modules
        learning such Saftey, Laws and Rules of our company.</p>
</div>
{% endblock page_header %}
{% block content %}
<h1>Modules </h1>
{% for module in module_list %}
<div class=" card mb-3">
    <div class="card-header">
        <a href="{% url 'blog:module-detail' module.pk %}" >{{ module.title }}</a>
    </div>
    <div class="card-body">
        <p>Instructor: <a href= "{% url 'blog:instructor-detail' module.instructor.pk %}">{{module.instructor}}</a> </p>
        <p>Summary: {{module.summary}}</p>
    </div>
</div>
{% empty %}
<p>There are no modules in the eTraining.</p>

{% endfor %}
{% endblock content %}

blog/templates/blog/new_module.html
{% extends "blog/base.html" %}
{% load bootstrap4 %}
{% block page_header %}

{% endblock page_header %}

{%block content %}
<h2>Add a new Module:</h2>

<form action= "{% url 'blog:new_module' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name= "submit" class= "btn btn-primary"> Add Module</button>
    {% endbuttons %}
</form>
{% endblock content%}